"""public_tenders_fields_institute_and_work_title

Revision ID: 0280041ec37e
Revises: 49bcecd37abf
Create Date: 2025-10-20 10:19:50.609509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0280041ec37e'
down_revision: Union[str, Sequence[str], None] = '49bcecd37abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_tenders', sa.Column('institute', sa.String(length=128), nullable=False))
    op.add_column('public_tenders', sa.Column('work_title', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_tenders', 'work_title')
    op.drop_column('public_tenders', 'institute')
    # ### end Alembic commands ###
