"""rate_log_add_public_tender_info

Revision ID: 03ffa92b585a
Revises: b0cf616d7b6f
Create Date: 2025-12-01 12:30:40.142695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ffa92b585a'
down_revision: Union[str, Sequence[str], None] = 'b0cf616d7b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_logs', sa.Column('public_tender_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_logs', 'public_tender_id')
    # ### end Alembic commands ###
