"""topic_table_law_link_optional_field

Revision ID: 1b341da90c7b
Revises: e6abd4bda705
Create Date: 2025-11-25 16:09:42.661246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b341da90c7b'
down_revision: Union[str, Sequence[str], None] = 'e6abd4bda705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('law_link', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'law_link')
    # ### end Alembic commands ###
