"""relationship_one_to_many_between_users_and_public_tenders

Revision ID: 534ef9cf5ba0
Revises: 9290c35bd5b3
Create Date: 2025-10-16 12:57:52.334803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534ef9cf5ba0'
down_revision: Union[str, Sequence[str], None] = '9290c35bd5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_tenders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'public_tenders', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_tenders', type_='foreignkey')
    op.drop_column('public_tenders', 'user_id')
    # ### end Alembic commands ###
