"""setting_enums_again

Revision ID: 56386f01ae66
Revises: 592af1fa7264
Create Date: 2025-11-01 11:01:52.472520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '56386f01ae66'
down_revision: Union[str, Sequence[str], None] = '592af1fa7264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


EnumCategory = sa.Enum('GENERAL', 'SPECIFIC', name='EnumCategory')
EnumStatus = sa.Enum('COMPLETE', 'INCOMPLETE', name='EnumStatus')
EnumGender = sa.Enum('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'category',
                    existing_type=sa.VARCHAR(length=32),
                    type_=EnumCategory,
                    existing_nullable=False,
                    postgresql_using='category::"EnumCategory"')
    op.alter_column('subjects', 'status',
                    existing_type=sa.VARCHAR(length=32),
                    type_=EnumStatus,
                    existing_nullable=False,
                    postgresql_using='status::"EnumStatus"')
    op.alter_column('topics', 'status',
                    existing_type=sa.VARCHAR(length=32),
                    type_=EnumStatus,
                    existing_nullable=False,
                    postgresql_using='status::"EnumStatus"')
    op.alter_column('users', 'gender',
                    existing_type=sa.VARCHAR(length=32),
                    type_=EnumGender,
                    existing_nullable=False,
                    postgresql_using = 'gender::"EnumGender"')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
                    existing_type=EnumGender,
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False,
                    postgresql_using='gender::varchar(32)')
    op.alter_column('topics', 'status',
                    existing_type=EnumStatus,
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False,
                    postgresql_using='status::varchar(32)')
    op.alter_column('subjects', 'status',
                    existing_type=EnumStatus,
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False,
                    postgresql_using='status::varchar(32)')
    op.alter_column('subjects', 'category',
                    existing_type=EnumCategory,
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False,
                    postgresql_using='category::varchar(32)')
    # ### end Alembic commands ###
