"""take_off_enums

Revision ID: 592af1fa7264
Revises: e9f532719e65
Create Date: 2025-11-01 10:44:38.636802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '592af1fa7264'
down_revision: Union[str, Sequence[str], None] = 'e9f532719e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'category',
               existing_type=postgresql.ENUM('GENERAL', 'SPECIFIC', name='EnumCategory'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('subjects', 'status',
               existing_type=postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='EnumStatus'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('topics', 'status',
               existing_type=postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='EnumStatusTopic'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender'),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender'),
               existing_nullable=False)
    op.alter_column('topics', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='EnumStatusTopic'),
               existing_nullable=False)
    op.alter_column('subjects', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='EnumStatus'),
               existing_nullable=False)
    op.alter_column('subjects', 'category',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('GENERAL', 'SPECIFIC', name='EnumCategory'),
               existing_nullable=False)
    # ### end Alembic commands ###
