"""descricao_to_description_in_notes

Revision ID: 5f17e24268b7
Revises: 6b4ae00e11a9
Create Date: 2025-10-16 14:16:55.243844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f17e24268b7'
down_revision: Union[str, Sequence[str], None] = '6b4ae00e11a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_subjects', sa.Column('description', sa.String(length=1024), nullable=False))
    op.drop_column('note_subjects', 'descricao')
    op.add_column('note_topics', sa.Column('description', sa.String(length=1024), nullable=False))
    op.drop_column('note_topics', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_topics', sa.Column('descricao', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('note_topics', 'description')
    op.add_column('note_subjects', sa.Column('descricao', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('note_subjects', 'description')
    # ### end Alembic commands ###
