"""enum_gender_added_to_users_table

Revision ID: 65d4d0e476aa
Revises: c4003bc8a29e
Create Date: 2025-10-16 11:39:18.262580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '65d4d0e476aa'
down_revision: Union[str, Sequence[str], None] = 'c4003bc8a29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EnumGender = sa.Enum('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender')


def upgrade() -> None:
    """Upgrade schema."""
    EnumGender.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender'),
               existing_nullable=False,
               postgresql_using = 'gender::"EnumGender"'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('FEMALE', 'MALE', 'NOT_BINARY', 'NOT_SAY', name='EnumGender'),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
