"""create_tables_notes_topics_and_subjects

Revision ID: 6b4ae00e11a9
Revises: 1a7f89000f15
Create Date: 2025-10-16 13:54:46.589551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4ae00e11a9'
down_revision: Union[str, Sequence[str], None] = '1a7f89000f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_subjects',
    sa.Column('note_subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1024), nullable=False),
    sa.Column('finish', sa.Boolean(), nullable=False),
    sa.Column('rate_success', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_subject_id')
    )
    op.create_table('note_topics',
    sa.Column('note_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1024), nullable=False),
    sa.Column('finish', sa.Boolean(), nullable=False),
    sa.Column('rate_success', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_topics')
    op.drop_table('note_subjects')
    # ### end Alembic commands ###
