"""subject_decimal_fulfillment_added

Revision ID: 6ec3804f4f64
Revises: 1b341da90c7b
Create Date: 2025-11-28 15:08:53.643553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec3804f4f64'
down_revision: Union[str, Sequence[str], None] = '1b341da90c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('fulfillment', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'fulfillment')
    # ### end Alembic commands ###
