"""create_table_subjects

Revision ID: 7471c3722e82
Revises: 534ef9cf5ba0
Create Date: 2025-10-16 13:11:47.494096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7471c3722e82'
down_revision: Union[str, Sequence[str], None] = '534ef9cf5ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_tender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum("GENERAL", "SPECIFIC", name="EnumCategory"), nullable=False),
    sa.Column('status', sa.Enum("COMPLETE", "INCOMPLETE", name="EnumStatus"), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['public_tender_id'], ['public_tenders.public_tender_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
