"""user_amdin_password_length_to_255

Revision ID: 8daa383dd507
Revises: 56386f01ae66
Create Date: 2025-11-01 11:56:20.460849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daa383dd507'
down_revision: Union[str, Sequence[str], None] = '56386f01ae66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_admin', 'password',
               existing_type=sa.VARCHAR(length=33),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_admin', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=33),
               existing_nullable=False)
    # ### end Alembic commands ###
