"""create_table_rate_logs

Revision ID: 8ee82c10dda6
Revises: 6ec3804f4f64
Create Date: 2025-11-28 16:37:03.706616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee82c10dda6'
down_revision: Union[str, Sequence[str], None] = '6ec3804f4f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_logs',
    sa.Column('rate_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subject', sa.Boolean(), nullable=True),
    sa.Column('topic', sa.Boolean(), nullable=True),
    sa.Column('note_subject', sa.Boolean(), nullable=True),
    sa.Column('note_topic', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_logs')
    # ### end Alembic commands ###
