"""create_table_public_tenders

Revision ID: 9290c35bd5b3
Revises: 65d4d0e476aa
Create Date: 2025-10-16 12:46:33.425956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9290c35bd5b3'
down_revision: Union[str, Sequence[str], None] = '65d4d0e476aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_tenders',
    sa.Column('public_tender_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_name', sa.String(length=255), nullable=False),
    sa.Column('tender_board', sa.String(length=255), nullable=False),
    sa.Column('notice_link', sa.String(length=1024), nullable=True),
    sa.Column('tender_date', sa.Date(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('public_tender_id')
    )
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.drop_table('public_tenders')
    # ### end Alembic commands ###
