"""rate_log_booleans_default_to_false

Revision ID: b0cf616d7b6f
Revises: f5c95d0aec2d
Create Date: 2025-11-28 18:11:31.303463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cf616d7b6f'
down_revision: Union[str, Sequence[str], None] = 'f5c95d0aec2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
