"""create_public_tender_board_table

Revision ID: b71d701a105f
Revises: e191fa49353c
Create Date: 2025-11-01 09:01:53.149366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b71d701a105f'
down_revision: Union[str, Sequence[str], None] = 'e191fa49353c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_tender_boards',
    sa.Column('public_tender_board_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sail', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('public_tender_board_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sail')
    )
    op.alter_column('note_subjects', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('note_topics', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pomodoros', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('public_tenders', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('study_tips', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subjects', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('topics', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('topics', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subjects', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('study_tips', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('public_tenders', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pomodoros', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('note_topics', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('note_subjects', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('public_tender_boards')
    # ### end Alembic commands ###
