"""added_column_name_to_notes_models

Revision ID: ba8130f76e08
Revises: 07e259e30c2a
Create Date: 2025-10-25 22:53:10.246181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8130f76e08'
down_revision: Union[str, Sequence[str], None] = '07e259e30c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_subjects', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('note_topics', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_topics', 'name')
    op.drop_column('note_subjects', 'name')
    # ### end Alembic commands ###
