"""public_tender_board_fix_user_admin_relationship

Revision ID: c6bd9deecb45
Revises: 8daa383dd507
Create Date: 2025-11-05 11:43:03.902248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bd9deecb45'
down_revision: Union[str, Sequence[str], None] = '8daa383dd507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
