"""create_table_pomodoro_relacted_to_user

Revision ID: e191fa49353c
Revises: ba8130f76e08
Create Date: 2025-10-29 11:43:14.825159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e191fa49353c'
down_revision: Union[str, Sequence[str], None] = 'ba8130f76e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoros',
    sa.Column('pomodoro_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pomodoro_name', sa.String(length=128), nullable=False),
    sa.Column('focus_minutes', sa.Integer(), nullable=False),
    sa.Column('focus_seconds', sa.Integer(), nullable=False),
    sa.Column('break_short', sa.Integer(), nullable=False),
    sa.Column('break_long', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pomodoro_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pomodoros')
    # ### end Alembic commands ###
