"""public_tender_enum_level_field

Revision ID: e6abd4bda705
Revises: c6bd9deecb45
Create Date: 2025-11-07 12:10:41.289997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6abd4bda705'
down_revision: Union[str, Sequence[str], None] = 'c6bd9deecb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


EnumLevel = sa.Enum('GRADUATED', 'HIGH_SCHOOL', name='EnumLevel')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    EnumLevel.create(op.get_bind())
    op.add_column('public_tenders', sa.Column('tender_level', EnumLevel, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_tenders', 'tender_level')
    EnumLevel.drop(op.get_bind())
    # ### end Alembic commands ###
