"""create_table_user_admin

Revision ID: e9f532719e65
Revises: b71d701a105f
Create Date: 2025-11-01 10:35:14.957328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f532719e65'
down_revision: Union[str, Sequence[str], None] = 'b71d701a105f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_admin',
    sa.Column('user_admin_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=33), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user_admin_id=1', name='user_admin_check'),
    sa.PrimaryKeyConstraint('user_admin_id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('public_tender_boards', sa.Column('user_admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'public_tender_boards', 'user_admin', ['user_admin_id'], ['user_admin_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_tender_boards', type_='foreignkey')
    op.drop_column('public_tender_boards', 'user_admin_id')
    op.drop_table('user_admin')
    # ### end Alembic commands ###
