"""rate_log_breaks_relationship_to_user

Revision ID: f5c95d0aec2d
Revises: 8ee82c10dda6
Create Date: 2025-11-28 17:55:53.278304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c95d0aec2d'
down_revision: Union[str, Sequence[str], None] = '8ee82c10dda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rate_logs_user_id_fkey'), 'rate_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('rate_logs_user_id_fkey'), 'rate_logs', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
